#+title: Bailey-Borwein-Plouffe
#+author: Daan van Berkel

The [[http://en.wikipedia.org/wiki/Bailey%25E2%2580%2593Borwein%25E2%2580%2593Plouffe_formula][Bailey-Borwein-Plouffe algorithm]] is an algorithm to calculate a
single digit of π, without calculating any of the preceding
digits. It is an example of a [[http://en.wikipedia.org/wiki/Spigot_algorithm][spigot algorithm]]. It is based on the
following formula for π

\[
\pi = \sum_{k=0}^{\infty}\frac{1}{16^{k}}\left(\frac{4}{8k+1} - \frac{2}{8k+4} - \frac{1}{8k+5} - \frac{1}{8k+6}\right)
\]

Finding this relation for π is an interesting application of the [[http://en.wikipedia.org/wiki/Integer_relation_algorithm][PSLQ
algorithm]], an algorithm for finding integer relations between real numbers.

* Motivation
Calculating the $d$-th hexadecimal-digit of $\pi$ amounts to
calculating the first digit of $16^{d-1}\pi$.

Concentrating on of the summands, we need to evaluate

\[
16^{d-1} \sum_{k=0}^{\infty} \frac{1}{16^{k}}\frac{4}{8k+1}
=
4\sum_{k=0}^{d-1}\frac{16^{d-1 - k}}{8k+1} + 4\sum_{k=d}^{\infty}\frac{1}{16^{k-d}}\frac{1}{8k+1}
\]

Because we are only interested in the fractional part we can further
simplify.

\[
\left\{\sum_{k=0}^{d-1}\frac{16^{d-1 - k}}{8k+1}\right\}
=
\sum_{k=0}^{d-1}\frac{16^{d-1 - k} \mod 8k+1}{8k+1}
\]
* Consideration
We have the following considerations.

** Fast Exponantiation
We should really implement fast exponantiation in such a way that is
can be used to to multiply different powers easily.
